---
name: "TestMacOs"

on:
  push

jobs:
  analyze:
    name: TestMacOs
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # We must fetch at least the immediate parents so that if this is
          # a pull request then we can checkout the head.
          fetch-depth: 2
          submodules: 'recursive'

      # Build picotls and picoquic.
      - run: |
          brew reinstall openssl
          export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
          ./ci/build_picotls.sh
          ./ci/build_picoquic.sh
     
      # Build fuzi_q and run tests
      - run: |
          mkdir build
          cd build
          export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
          cmake ..
          cmake --build .
          make
          ulimit -c unlimited -S
          pwd
          ./fuzi_qt -P ../../picoquic && QRQRESULT=$? 
          if [ "${QRQRESULT}" == 0 ]; then exit 0; fi;
          exit 1

